//
// TestObject.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct TestObject: Codable, Hashable {

    public var property: String?

    public init(property: String? = nil) {
        self.property = property
    }

}

